# Railway deployment configuration
[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"

[deploy.env]
# Production environment variables
PORT = "8000"
EMOTION_MODEL_DEVICE = "cpu"
EMOTION_MODEL_CACHE_DIR = "/tmp/model_cache"
TRANSFORMERS_CACHE = "/tmp/transformers_cache"
