"""initial schema

Revision ID: 52ce5d2d31e1
Revises: 
Create Date: 2026-07-03 12:07:49.625983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database

# revision identifiers, used by Alembic.
revision: str = '52ce5d2d31e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('emotion_analyses',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('user_id', app.database.GUID(), nullable=False),
    sa.Column('analysis_type', sa.Enum('TEXT', 'VIDEO', 'AUDIO', 'IMAGE', name='analysistype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='analysisstatus'), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('input_file_path', sa.String(length=500), nullable=True),
    sa.Column('input_file_name', sa.String(length=255), nullable=True),
    sa.Column('input_file_size', sa.Integer(), nullable=True),
    sa.Column('processing_duration', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('dominant_emotion', sa.Enum('JOY', 'SADNESS', 'ANGER', 'FEAR', 'SURPRISE', 'DISGUST', 'LOVE', 'EXCITEMENT', 'NEUTRAL', name='emotionlabel'), nullable=True),
    sa.Column('dominant_emotion_confidence', sa.Float(), nullable=True),
    sa.Column('emotion_scores', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('arousal_score', sa.Float(), nullable=True),
    sa.Column('valence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emotion_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emotion_analyses'))
    )
    with op.batch_alter_table('emotion_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotion_analyses_analysis_type'), ['analysis_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotion_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotion_analyses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotion_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('audio_segment_analyses',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('analysis_id', app.database.GUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('audio_features', sa.JSON(), nullable=True),
    sa.Column('dominant_emotion', sa.Enum('JOY', 'SADNESS', 'ANGER', 'FEAR', 'SURPRISE', 'DISGUST', 'LOVE', 'EXCITEMENT', 'NEUTRAL', name='emotionlabel'), nullable=True),
    sa.Column('emotion_scores', sa.JSON(), nullable=True),
    sa.Column('transcribed_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['emotion_analyses.id'], name=op.f('fk_audio_segment_analyses_analysis_id_emotion_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_segment_analyses'))
    )
    with op.batch_alter_table('audio_segment_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_segment_analyses_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('text_segment_analyses',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('analysis_id', app.database.GUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('segment_text', sa.Text(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('end_position', sa.Integer(), nullable=True),
    sa.Column('dominant_emotion', sa.Enum('JOY', 'SADNESS', 'ANGER', 'FEAR', 'SURPRISE', 'DISGUST', 'LOVE', 'EXCITEMENT', 'NEUTRAL', name='emotionlabel'), nullable=True),
    sa.Column('emotion_scores', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['emotion_analyses.id'], name=op.f('fk_text_segment_analyses_analysis_id_emotion_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text_segment_analyses'))
    )
    with op.batch_alter_table('text_segment_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_segment_analyses_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('video_frame_analyses',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('analysis_id', app.database.GUID(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('faces_detected', sa.Integer(), nullable=True),
    sa.Column('face_locations', sa.JSON(), nullable=True),
    sa.Column('emotions_per_face', sa.JSON(), nullable=True),
    sa.Column('dominant_emotion', sa.Enum('JOY', 'SADNESS', 'ANGER', 'FEAR', 'SURPRISE', 'DISGUST', 'LOVE', 'EXCITEMENT', 'NEUTRAL', name='emotionlabel'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['emotion_analyses.id'], name=op.f('fk_video_frame_analyses_analysis_id_emotion_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_frame_analyses'))
    )
    with op.batch_alter_table('video_frame_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_frame_analyses_analysis_id'), ['analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_frame_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_frame_analyses_analysis_id'))

    op.drop_table('video_frame_analyses')
    with op.batch_alter_table('text_segment_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_segment_analyses_analysis_id'))

    op.drop_table('text_segment_analyses')
    with op.batch_alter_table('audio_segment_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_segment_analyses_analysis_id'))

    op.drop_table('audio_segment_analyses')
    with op.batch_alter_table('emotion_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotion_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_emotion_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_emotion_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_emotion_analyses_analysis_type'))

    op.drop_table('emotion_analyses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
